apiVersion: v1
kind: ConfigMap
metadata:
  name: chargegrid-env
  labels: {{- include "cg.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chargegrid
  labels: {{- include "cg.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
{{- if .Values.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chargegrid-secrets
  labels: {{- include "cg.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef: { name: {{ .Values.externalSecret.store }}, kind: ClusterSecretStore }
  target: { name: {{ .Values.secretName }} }
  dataFrom:
    - extract: { key: {{ .Values.externalSecret.remoteKey }} }
{{- end }}
