"""phase 7 site config

Revision ID: 05102ae248e1
Revises: 082d69623b4c
Create Date: 2026-09-25 21:30:50.399232

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05102ae248e1"
down_revision: str | None = "082d69623b4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_config",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("optimisation_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("subsidy", sa.Boolean(), nullable=False),
        sa.Column("sizing", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("finance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("placeholders", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["optimisation_id"], ["optimisation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["candidate_site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_site_config_optimisation_id"), "site_config", ["optimisation_id"], unique=False
    )
    op.create_index(
        "site_config_unique_idx",
        "site_config",
        ["optimisation_id", "site_id", "subsidy"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("site_config_unique_idx", table_name="site_config")
    op.drop_index(op.f("ix_site_config_optimisation_id"), table_name="site_config")
    op.drop_table("site_config")
    # ### end Alembic commands ###
