"""planning run task id

Revision ID: 082d69623b4c
Revises: 82240110d16f
Create Date: 2026-09-25 19:14:44.032146

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "082d69623b4c"
down_revision: str | None = "82240110d16f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("planning_run", sa.Column("task_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("planning_run", "task_id")
    # ### end Alembic commands ###
