"""phase 10 grid assets and operator observations

Revision ID: 11250a6128ea
Revises: 4f4e48be289a
Create Date: 2026-09-27 05:37:36.885402

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11250a6128ea"
down_revision: str | None = "4f4e48be289a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "station_prediction",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("calibration_run", sa.Text(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("observed_kwh_per_day", sa.Float(), nullable=False),
        sa.Column("parametric_kwh_per_day", sa.Float(), nullable=False),
        sa.Column("calibrated_kwh_per_day", sa.Float(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["station_id"], ["charging_station.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_station_prediction_calibration_run"),
        "station_prediction",
        ["calibration_run"],
        unique=False,
    )
    op.create_index(
        op.f("ix_station_prediction_station_id"), "station_prediction", ["station_id"], unique=False
    )
    op.create_table(
        "station_utilisation_daily",
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("kwh", sa.Float(), nullable=False),
        sa.Column("sessions", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["station_id"], ["charging_station.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("station_id", "day"),
    )
    op.create_table(
        "charging_session_obs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("location_id", sa.Text(), nullable=False),
        sa.Column("evse_uid", sa.Text(), nullable=True),
        sa.Column("station_id", sa.UUID(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("kwh", sa.Float(), nullable=False),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("snapshot_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["snapshot_id"], ["dataset_snapshot.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["station_id"], ["charging_station.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "kind", "external_id"),
    )
    op.create_index(
        op.f("ix_charging_session_obs_source_id"),
        "charging_session_obs",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_charging_session_obs_station_id"),
        "charging_session_obs",
        ["station_id"],
        unique=False,
    )
    op.create_table(
        "grid_asset_rated",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("discom", sa.Text(), nullable=False),
        sa.Column("asset_type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("voltage_kv", sa.Float(), nullable=True),
        sa.Column("rated_kva", sa.Float(), nullable=False),
        sa.Column("loading_limit", sa.Float(), nullable=True),
        sa.Column("base_peak_kva", sa.Float(), nullable=False),
        sa.Column("base_hourly_kva", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("measured_on", sa.Date(), nullable=True),
        sa.Column("license_class", sa.Text(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["snapshot_id"], ["dataset_snapshot.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grid_asset_rated_discom"), "grid_asset_rated", ["discom"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_grid_asset_rated_discom"), table_name="grid_asset_rated")
    op.drop_table("grid_asset_rated")
    op.drop_index(op.f("ix_charging_session_obs_station_id"), table_name="charging_session_obs")
    op.drop_index(op.f("ix_charging_session_obs_source_id"), table_name="charging_session_obs")
    op.drop_table("charging_session_obs")
    op.drop_table("station_utilisation_daily")
    op.drop_index(op.f("ix_station_prediction_station_id"), table_name="station_prediction")
    op.drop_index(op.f("ix_station_prediction_calibration_run"), table_name="station_prediction")
    op.drop_table("station_prediction")
    # ### end Alembic commands ###
