"""region cell membership

Revision ID: 4304f49e0f44
Revises: cbd9db964901
Create Date: 2026-09-27 04:22:13.650595

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


class H3Index(sa.types.UserDefinedType):  # type: ignore[type-arg]
    """The h3-pg `h3index` type (migrations don't import app code)."""

    cache_ok = True

    def get_col_spec(self) -> str:
        return "h3index"


# revision identifiers, used by Alembic.
revision: str = "4304f49e0f44"
down_revision: str | None = "cbd9db964901"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "region_cell",
        sa.Column("region_id", sa.Text(), nullable=False),
        sa.Column("h3", H3Index(), nullable=False),
        sa.PrimaryKeyConstraint("region_id", "h3"),
    )
    # Existing cells keep the region they were created for.
    op.execute("insert into region_cell (region_id, h3) select region_id, h3 from h3_cell")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("region_cell")
    # ### end Alembic commands ###
