"""phase 4 planning runs and candidates

Scenario, planning_run, candidate_site, feasibility_result, site_feature.
Geometry uses spatial_index=False: the GIST index is created explicitly below.

Revision ID: 4d36d986dda0
Revises: a9ca61888466
Create Date: 2026-09-25 14:31:39.380837

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d36d986dda0"
down_revision: str | None = "a9ca61888466"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenario",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("region_id", sa.Text(), nullable=False),
        sa.Column("target_year", sa.Integer(), nullable=False),
        sa.Column("adoption_case", sa.Text(), nullable=False),
        sa.Column("adoption_multiplier", sa.Float(), nullable=False),
        sa.Column("charger_classes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("segments", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("budget_inr", sa.BigInteger(), nullable=True),
        sa.Column("weight_profile_id", sa.Text(), nullable=True),
        sa.Column("constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "planning_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("model_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("git_sha", sa.Text(), nullable=True),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("funnel", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planning_run_scenario_id"), "planning_run", ["scenario_id"], unique=False
    )
    op.create_table(
        "candidate_site",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_run", sa.UUID(), nullable=False),
        sa.Column("region_id", sa.Text(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                spatial_index=False,
            ),
            nullable=False,
        ),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("merged_origins", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("host_poi_id", sa.Text(), nullable=True),
        sa.Column("host_type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_run"], ["planning_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_candidate_site_geom", "candidate_site", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_index(
        "ix_candidate_site_run_status", "candidate_site", ["created_by_run", "status"], unique=False
    )
    op.create_table(
        "feasibility_result",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("reason_codes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["candidate_site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("site_id"),
    )
    op.create_table(
        "site_feature",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("scenario", sa.Text(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["candidate_site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("site_id", "year", "scenario"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_feature")
    op.drop_table("feasibility_result")
    op.drop_index("ix_candidate_site_run_status", table_name="candidate_site")
    op.drop_index("idx_candidate_site_geom", table_name="candidate_site", postgresql_using="gist")
    op.drop_table("candidate_site")
    op.drop_index(op.f("ix_planning_run_scenario_id"), table_name="planning_run")
    op.drop_table("planning_run")
    op.drop_table("scenario")
    # ### end Alembic commands ###
