"""osm place gazetteer

Revision ID: 4f4e48be289a
Revises: 95e02ae418f7
Create Date: 2026-09-27 04:51:32.616952

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f4e48be289a"
down_revision: str | None = "95e02ae418f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "osm_place",
        sa.Column("osm_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_en", sa.Text(), nullable=True),
        sa.Column("place", sa.Text(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("alt_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("osm_id"),
    )
    op.create_index(op.f("ix_osm_place_name"), "osm_place", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_osm_place_name"), table_name="osm_place")
    op.drop_table("osm_place")
    # ### end Alembic commands ###
