"""phase 5 site catchment and run site

Revision ID: 54b1f043b626
Revises: 4d36d986dda0
Create Date: 2026-09-25 15:05:19.714508

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54b1f043b626"
down_revision: str | None = "4d36d986dda0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_site",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("phase_year", sa.Integer(), nullable=True),
        sa.Column("score_total", sa.Float(), nullable=True),
        sa.Column("sub_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("robustness", sa.Float(), nullable=True),
        sa.Column("coverage_kwh", sa.Float(), nullable=True),
        sa.Column("served_population", sa.Float(), nullable=True),
        sa.Column("why_not", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["planning_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["candidate_site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "site_id"),
    )
    op.create_index("run_site_run_rank_idx", "run_site", ["run_id", "rank"], unique=False)
    op.create_table(
        "site_catchment",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("h3_cells", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["candidate_site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("site_id"),
    )
    op.create_index(
        "site_catchment_geom_idx", "site_catchment", ["geom"], unique=False, postgresql_using="gist"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("site_catchment_geom_idx", table_name="site_catchment", postgresql_using="gist")
    op.drop_table("site_catchment")
    op.drop_index("run_site_run_rank_idx", table_name="run_site")
    op.drop_table("run_site")
    # ### end Alembic commands ###
