"""phase 11 orgs roles audit config versions

Revision ID: 7486d4558b2c
Revises: 11250a6128ea
Create Date: 2026-09-27 09:56:54.331851

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7486d4558b2c"
down_revision: str | None = "11250a6128ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.Text(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=True),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_at"), "audit_log", ["at"], unique=False)
    op.create_index(op.f("ix_audit_log_org_id"), "audit_log", ["org_id"], unique=False)
    op.create_table(
        "config_version",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("author_label", sa.Text(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "version"),
    )
    op.create_index(op.f("ix_config_version_key"), "config_version", ["key"], unique=False)
    op.create_table(
        "org",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "role_binding",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "org_id"),
    )
    op.add_column("agent_session", sa.Column("org_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_agent_session_org_id"), "agent_session", ["org_id"], unique=False)
    op.add_column("app_user", sa.Column("oidc_subject", sa.Text(), nullable=True))
    op.add_column("app_user", sa.Column("display_name", sa.Text(), nullable=True))
    op.create_unique_constraint("uq_app_user_oidc_subject", "app_user", ["oidc_subject"])
    op.add_column("scenario", sa.Column("org_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_scenario_org_id"), "scenario", ["org_id"], unique=False)
    op.create_foreign_key(
        "fk_scenario_org", "scenario", "org", ["org_id"], ["id"], ondelete="SET NULL"
    )
    # Everything created before orgs existed belongs to the default org.
    op.execute(
        "insert into org (id, slug, name, created_at, updated_at) values "
        "(gen_random_uuid(), 'default', 'Default organisation', now(), now()) "
        "on conflict (slug) do nothing"
    )
    op.execute(
        "update scenario set org_id = (select id from org where slug = 'default') "
        "where org_id is null"
    )
    op.execute(
        "update agent_session set org_id = (select id from org where slug = 'default') "
        "where org_id is null"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_scenario_org", "scenario", type_="foreignkey")
    op.drop_index(op.f("ix_scenario_org_id"), table_name="scenario")
    op.drop_column("scenario", "org_id")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("uq_app_user_oidc_subject", "app_user", type_="unique")
    op.drop_column("app_user", "display_name")
    op.drop_column("app_user", "oidc_subject")
    op.drop_index(op.f("ix_agent_session_org_id"), table_name="agent_session")
    op.drop_column("agent_session", "org_id")
    op.drop_table("role_binding")
    op.drop_table("org")
    op.drop_index(op.f("ix_config_version_key"), table_name="config_version")
    op.drop_table("config_version")
    op.drop_index(op.f("ix_audit_log_org_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
