"""phase 6 optimisation

Revision ID: 82240110d16f
Revises: 54b1f043b626
Create Date: 2026-09-25 18:10:14.638750

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82240110d16f"
down_revision: str | None = "54b1f043b626"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "optimisation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("strategy", sa.Text(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("solver_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("kpis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("on_front", sa.Boolean(), nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cell_assignment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("drive_time_voronoi", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["planning_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_optimisation_run_id"), "optimisation", ["run_id"], unique=False)
    op.create_table(
        "optimisation_site",
        sa.Column("optimisation_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("bundle", sa.Text(), nullable=False),
        sa.Column("charge_points", sa.Integer(), nullable=False),
        sa.Column("cost_inr", sa.Float(), nullable=False),
        sa.Column("capacity_kwh", sa.Float(), nullable=False),
        sa.Column("served_kwh", sa.Float(), nullable=False),
        sa.Column("served_population", sa.Float(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["optimisation_id"], ["optimisation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["candidate_site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("optimisation_id", "site_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("optimisation_site")
    op.drop_index(op.f("ix_optimisation_run_id"), table_name="optimisation")
    op.drop_table("optimisation")
    # ### end Alembic commands ###
