"""phase 3 demand outputs

Revision ID: a9ca61888466
Revises: e0527ce1e194
Create Date: 2026-09-25 14:03:55.883243

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9ca61888466"
down_revision: str | None = "e0527ce1e194"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("h3_cell_feature", sa.Column("ev_stock_p10", sa.Float(), nullable=True))
    op.add_column("h3_cell_feature", sa.Column("ev_stock_p50", sa.Float(), nullable=True))
    op.add_column("h3_cell_feature", sa.Column("ev_stock_p90", sa.Float(), nullable=True))
    op.add_column(
        "h3_cell_feature",
        sa.Column("ev_stock_by_segment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("h3_cell_feature", sa.Column("public_kwh_p10", sa.Float(), nullable=True))
    op.add_column("h3_cell_feature", sa.Column("public_kwh_p50", sa.Float(), nullable=True))
    op.add_column("h3_cell_feature", sa.Column("public_kwh_p90", sa.Float(), nullable=True))
    op.add_column("h3_cell_feature", sa.Column("sessions_p50", sa.Float(), nullable=True))
    op.add_column("h3_cell_feature", sa.Column("access_ratio", sa.Float(), nullable=True))
    op.add_column("h3_cell_feature", sa.Column("served_kwh", sa.Float(), nullable=True))
    op.add_column("h3_cell_feature", sa.Column("gap_kwh", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("h3_cell_feature", "gap_kwh")
    op.drop_column("h3_cell_feature", "served_kwh")
    op.drop_column("h3_cell_feature", "access_ratio")
    op.drop_column("h3_cell_feature", "sessions_p50")
    op.drop_column("h3_cell_feature", "public_kwh_p90")
    op.drop_column("h3_cell_feature", "public_kwh_p50")
    op.drop_column("h3_cell_feature", "public_kwh_p10")
    op.drop_column("h3_cell_feature", "ev_stock_by_segment")
    op.drop_column("h3_cell_feature", "ev_stock_p90")
    op.drop_column("h3_cell_feature", "ev_stock_p50")
    op.drop_column("h3_cell_feature", "ev_stock_p10")
    # ### end Alembic commands ###
