"""phase 2 data layer

Provenance (data_source, dataset_snapshot, evidence, api_usage), fused
charging stations (charging_station, evse, connector, station_source_link,
charger_source_record), and demand inputs (vehicle_registration_agg,
rto_area_map, h3_cell, h3_cell_feature).

Geometry columns use spatial_index=False because the GIST indexes are
created explicitly below; letting GeoAlchemy2 add them too would duplicate them.

Revision ID: e0527ce1e194
Revises: 4fe7edb3b871
Create Date: 2026-09-24 18:32:20.659804

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


class H3Index(sa.types.UserDefinedType):  # type: ignore[type-arg]
    """Frozen copy of the h3-pg column type, so this migration never imports app code."""

    cache_ok = True

    def get_col_spec(self, **kw: object) -> str:
        return "h3index"


# revision identifiers, used by Alembic.
revision: str = "e0527ce1e194"
down_revision: str | None = "4fe7edb3b871"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_usage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("sku", sa.Text(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("cost_inr", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_usage_provider"), "api_usage", ["provider"], unique=False)
    op.create_index(op.f("ix_api_usage_ts"), "api_usage", ["ts"], unique=False)
    op.create_table(
        "charging_station",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("operator", sa.Text(), nullable=True),
        sa.Column("host_type", sa.Text(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                spatial_index=False,
            ),
            nullable=False,
        ),
        sa.Column("access", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("opening_hours", sa.Text(), nullable=True),
        sa.Column("license_class", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Text(), nullable=False),
        sa.Column("conflicts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_charging_station_geom",
        "charging_station",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_charging_station_operator"), "charging_station", ["operator"], unique=False
    )
    op.create_table(
        "data_source",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("license_class", sa.Text(), nullable=False),
        sa.Column("license_text", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("terms_url", sa.Text(), nullable=True),
        sa.Column("refresh_cadence", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_type", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("value_num", sa.Float(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("p10", sa.Float(), nullable=True),
        sa.Column("p90", sa.Float(), nullable=True),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("snapshot_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("confidence", sa.Text(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_evidence_subject", "evidence", ["subject_type", "subject_id"], unique=False)
    op.create_table(
        "h3_cell",
        sa.Column("h3", H3Index(), nullable=False),
        sa.Column("res", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Text(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                spatial_index=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("h3"),
    )
    op.create_index("idx_h3_cell_geom", "h3_cell", ["geom"], unique=False, postgresql_using="gist")
    op.create_index(op.f("ix_h3_cell_region_id"), "h3_cell", ["region_id"], unique=False)
    op.create_table(
        "h3_cell_feature",
        sa.Column("h3", H3Index(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("scenario", sa.Text(), nullable=False),
        sa.Column("population", sa.Float(), nullable=True),
        sa.Column("snapshot_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("h3", "year", "scenario"),
    )
    op.create_table(
        "rto_area_map",
        sa.Column("rto_code", sa.Text(), nullable=False),
        sa.Column("admin_boundary_id", sa.BigInteger(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("rto_code", "admin_boundary_id"),
    )
    op.create_table(
        "dataset_snapshot",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("granularity", sa.Text(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("storage_uri", sa.Text(), nullable=True),
        sa.Column("checksum", sa.Text(), nullable=True),
        sa.Column("quality_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dataset_snapshot_source_id"), "dataset_snapshot", ["source_id"], unique=False
    )
    op.create_table(
        "evse",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("max_kw", sa.Float(), nullable=True),
        sa.Column("current", sa.Text(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["station_id"], ["charging_station.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evse_station_id"), "evse", ["station_id"], unique=False)
    op.create_table(
        "charger_source_record",
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_record_id", sa.Text(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("record", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                spatial_index=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["dataset_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
        ),
        sa.PrimaryKeyConstraint("source_id", "source_record_id"),
    )
    op.create_index(
        "idx_charger_source_record_geom",
        "charger_source_record",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "connector",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evse_id", sa.UUID(), nullable=False),
        sa.Column("standard", sa.Text(), nullable=False),
        sa.Column("max_kw", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["evse_id"], ["evse.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connector_evse_id"), "connector", ["evse_id"], unique=False)
    op.create_table(
        "station_source_link",
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_record_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("record", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["dataset_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_source.id"],
        ),
        sa.ForeignKeyConstraint(["station_id"], ["charging_station.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_id", "source_record_id"),
    )
    op.create_index(
        op.f("ix_station_source_link_station_id"),
        "station_source_link",
        ["station_id"],
        unique=False,
    )
    op.create_table(
        "vehicle_registration_agg",
        sa.Column("rto_code", sa.Text(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("fuel", sa.Text(), nullable=False),
        sa.Column("vehicle_class", sa.Text(), nullable=False),
        sa.Column("segment", sa.Text(), nullable=False),
        sa.Column("ev_type", sa.Text(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["dataset_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("rto_code", "month", "fuel", "vehicle_class"),
    )
    op.create_index(
        op.f("ix_vehicle_registration_agg_snapshot_id"),
        "vehicle_registration_agg",
        ["snapshot_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vehicle_registration_agg_snapshot_id"), table_name="vehicle_registration_agg"
    )
    op.drop_table("vehicle_registration_agg")
    op.drop_index(op.f("ix_station_source_link_station_id"), table_name="station_source_link")
    op.drop_table("station_source_link")
    op.drop_index(op.f("ix_connector_evse_id"), table_name="connector")
    op.drop_table("connector")
    op.drop_index(
        "idx_charger_source_record_geom",
        table_name="charger_source_record",
        postgresql_using="gist",
    )
    op.drop_table("charger_source_record")
    op.drop_index(op.f("ix_evse_station_id"), table_name="evse")
    op.drop_table("evse")
    op.drop_index(op.f("ix_dataset_snapshot_source_id"), table_name="dataset_snapshot")
    op.drop_table("dataset_snapshot")
    op.drop_table("rto_area_map")
    op.drop_table("h3_cell_feature")
    op.drop_index(op.f("ix_h3_cell_region_id"), table_name="h3_cell")
    op.drop_index("idx_h3_cell_geom", table_name="h3_cell", postgresql_using="gist")
    op.drop_table("h3_cell")
    op.drop_index("ix_evidence_subject", table_name="evidence")
    op.drop_table("evidence")
    op.drop_table("data_source")
    op.drop_index(op.f("ix_charging_station_operator"), table_name="charging_station")
    op.drop_index(
        "idx_charging_station_geom", table_name="charging_station", postgresql_using="gist"
    )
    op.drop_table("charging_station")
    op.drop_index(op.f("ix_api_usage_ts"), table_name="api_usage")
    op.drop_index(op.f("ix_api_usage_provider"), table_name="api_usage")
    op.drop_table("api_usage")
    # ### end Alembic commands ###
